version: "3.2"

services:

  php:
    container_name: php
    build:
      context: ./docker/php
    restart: always
    volumes:
      - ./:/var/www/html
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d

  nginx:
    container_name: nginx
    image: library/nginx:1.18.0
    restart: always
    depends_on:
      - php
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      #- ./docker/nginx/ssl:/etc/nginx/ssl
    links:
      - php

  redis:
    container_name: redis
    image: library/redis:6.0.1
    restart: always
    links:
      - php

  mysql:
    container_name: mysql-teste
    image: library/mysql:8.0.20
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    container_name: adminer
    image: library/adminer:4.7.7
    restart: always
    ports:
      - 9090:9090
    depends_on:
      - mysql
    links:
      - mysql