version: "3.2"

services:

  php:
    container_name: php
    build:
      context: ./docker/php
    restart: always
    volumes:
      - ./:/var/www/html
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d

  nginx:
    container_name: nginx
    image: library/nginx:1.18.0
    restart: always
    depends_on:
      - php
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      #- ./docker/nginx/ssl:/etc/nginx/ssl
    links:
      - php

  redis:
    container_name: redis
    image: library/redis:6.0.1
    restart: always
    links:
      - php

  mysql:
    container_name: mysql
    image: library/mysql:8.0.20
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=local_develop
    volumes:
      - data-mysql:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:fpm-alpine
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 8181:80
    links:
      - mysql

volumes:
  data-mysql: {}